### ISSUE TITLE
Unable to read host override, got error: unable to find resource. it may have been deleted upstream

### ISSUE THREAD

**Issue by k-kingsley** [browningluke/terraform-provider-opnsense#14]
One of my host overrides was deleted manually. I get the following error when i attempt to run `terraform apply`:
```
╷
│ Error: Client Error
│ 
│   with opnsense_unbound_host_override.AAAA_record,
│   on main.tf line 2, in resource "opnsense_unbound_host_override" "AAAA_record":
│    2: resource "opnsense_unbound_host_override" "AAAA_record" {
│ 
│ Unable to read host override, got error: unable to find resource. it may have been deleted upstream
╵
```

I would expect the record to be recreated as defined in the state.

snippet from my main.tf:
```
resource "opnsense_unbound_host_override" "AAAA_record" {
  enabled = true
  type = "AAAA"
  hostname = "k8s-master"
  domain = "REDACTED"
  server = "REDACTED"
}

```

snippet from my provider.tf:
```
provider "opnsense" {
  uri = "https://192.168.1.1"
  allow_insecure = true
  api_key = "REDACTED"
  api_secret = "REDACTED"
}
```

In order to resolve the issue I had to target the specific resource for removal with the `terraform state rm` command and then run `terraform apply` again

**Comment by browningluke** [comment]
Hey there @k-kingsley, sorry for the delay. This is a known issue at the moment, since not handling remote changes makes the initial development easier.

I guarantee this will be fixed when the handling is correctly implemented, but I'm afraid I can't give you a timeline of when that will happen.

**Comment by browningluke** [comment]
Hi @k-kingsley. This is now handled correctly in versions >=0.3.1 of this provider.

I'll close this issue, but if you run into any bugs, any comments or issues are very welcome!
