### ISSUE TITLE
Interested on Wireguard API

### ISSUE THREAD

**Issue by achetronic** [browningluke/terraform-provider-opnsense#27]
Hello there :)

As you probably know, most users of this provider are homlab-ers that have an infra too-pro-to-be-at-home. Honestly, one of the best features in this regard is having a VPN right in the firewall, but right now everything is manually configured.

I would love to have [some support for this API](https://docs.opnsense.org/development/api/plugins/wireguard.html)

WDYT?

**Comment by browningluke** [comment]
Hey @achetronic, thank you for raising an issue. 

I will definitely look into this! Most of the prioritisation so far has been based on my own usage, so I'll be sure to priorize this. 

I'm currently unavailable for the next few days, so I can't give you an accurate ETA. I reckon it _should_ be done in the next few weeks.

**Comment by achetronic** [comment]
> Hey @achetronic, thank you for raising an issue.
> 
> I will definitely look into this! Most of the prioritisation so far has been based on my own usage, so I'll be sure to priorize this.
> 
> I'm currently unavailable for the next few days, so I can't give you an accurate ETA. I reckon it _should_ be done in the next few weeks.

Hey, thank you for answering :)

Honestly, this provider cover a lot of things, so please, don't put any pressure over you, not anything. Another cool feature I would love to, is to manage BGP plugin with is, as it could manage neighbors just before configuring MetalLB on bare metal environments used for Kubernetes. Anyway, thank you in advance mate, this is a great job

**Comment by browningluke** [comment]
Hey there @achetronic 

I've just released v0.7.0 which has the [wireguard resources](https://registry.terraform.io/providers/browningluke/opnsense/latest/docs/resources/wireguard_server). Give it a go whenever you get time and let me know if you run into any issues!

I'm also looking into adding the BGP resources, but I'm not too sure when I'll be able to get around to implementing it.

**Comment by browningluke** [comment]
Managed to get some BGP resources out in v0.8.0 too! Give them a go when you get some time, hopefully they work for you :)
