### ISSUE TITLE
Support for interfaces

### ISSUE THREAD

**Issue by rcloran** [browningluke/terraform-provider-opnsense#33]
I'm interested in being able to get information from my interfaces, such as assigned IP addresses.

It looks like this is only available read-only in the OPNSense API: https://docs.opnsense.org/development/api/core/diagnostics.html (InterfaceController.php)

I think this means that it should only be available by a data source, eg:

```
data "opnsense_interface" "igc0" {
  name = "igc0"
}
```

I'm imagining that I could then be able to get access to the data returned by getInterfaceConfig. 

Would adding this fit in to your goal with this project? I'd be happy to put in the legwork to implement it if so. I'm kinda new to Terraform, and not super proficient in Go, so might need a little hand holding along the way. I'm also definitely happy to do something different to the API proposed above.

**Comment by rcloran** [comment]
I've put together a minimum working implementation ... still lots that I think needs to be cleaned up (and documentation written, etc)

https://github.com/rcloran/opnsense-go/commit/2f1767a54c40e37c561d1f58aa0a739db2b0fba1
https://github.com/rcloran/terraform-provider-opnsense/commit/f4e91a35d75721fb04e07fe7a7d396731b842b3a

And a demonstration outputting a few different interface types on my router

```
data "opnsense_interface" "igc0" {
  device = "igc0"
}

output "igc0" {
  value = data.opnsense_interface.igc0
}

data "opnsense_interface" "igc1_vlan8" {
  device = "igc1_vlan8"
}

output "igc1_vlan8" {
  value = data.opnsense_interface.igc1_vlan8
}

data "opnsense_interface" "wg1" {
  device = "wg1"
}

output "wg1" {
  value = data.opnsense_interface.wg1
}
```

Produces: https://gist.github.com/rcloran/067f14843d462628365292116ac0d13f

**Comment by browningluke** [comment]
Hey there @rcloran, this is great! Thank you so much for this!

In the opnsense-go repo I've been using some Go code to generate the schema (haven't published it to the repo yet, bad practice I know...) so I'll need to refactor it slightly to generate these more complex data types. Shouldn't be too much work, and the initial legwork you've done will be a big help!

Will try to get this out in a release in the next couple of days.

**Comment by rcloran** [comment]
> In the opnsense-go repo I've been using some Go code to generate the schema (haven't published it to the repo yet, bad practice I know...) so I'll need to refactor it slightly to generate these more complex data types.

(y) I also implemented them in a pretty random order, so I expect you'll see quite a lot of difference in the schema :)

> Will try to get this out in a release in the next couple of days.

Great! I'm happy to do any other work that needs to be done to get this complete, if you want.

**Comment by browningluke** [comment]
Hi @rcloran, these changes should be out now in v0.9.0. Give it a try and let me know :)

Thanks once again for your help!

**Comment by rcloran** [comment]
Works perfectly for what I wanted, thanks so much!
