### ISSUE TITLE
opnsense_firewall_filter not accepting destination port range

### ISSUE THREAD

**Issue by chrisreeves-** [browningluke/terraform-provider-opnsense#34]
Problem Statement: When using the `opnsense_firewall_filter` resource, the documentation advises a port range can be used by utilising the `-` such as `1024-65535` however it returns an error.

Attempts: I've tried using an alias defining the ports but it also doesn't work, I've tried wrapping "" and [] around it too.

Code:
![image](https://github.com/browningluke/terraform-provider-opnsense/assets/9957942/35d0cc06-4368-4f25-874a-ef868dec2a2c)

Error:
![image](https://github.com/browningluke/terraform-provider-opnsense/assets/9957942/8c076458-e5ae-4a7d-8ac1-9d3726f807af)

**Comment by browningluke** [comment]
Hey @chrisreeves-, thanks for opening this issue!

Unfortunately this is an oversight of how this resource was implemented. Even though the docs say that this is possible, because the destination.port is expecting an integer, it fails.

I'll get working on a fix, should be out in a few days. However it may result in you having to remove & import the existing rules you've created, since the schema will change slightly. Sorry about that!

**Comment by chrisreeves-** [comment]
All good @browningluke thanks for your extremely fast response! :) :)

The provider is ssooooo good so thanks for all the hard work you've put into it to date!

**Comment by browningluke** [comment]
Hey there @chrisreeves- , this should be fixed in v0.9.0. I'll close this issue now, but feel free to re-open it if you still run into issues!

Just for clarity's sake, this is how you define port ranges now:
```tf
  destination = {
    net  = "192.168.0.1"
    port = "80-443"
  }
```

**Comment by chrisreeves-** [comment]
Hey @browningluke it still seems to be an issue in `0.9.0`

![image](https://github.com/browningluke/terraform-provider-opnsense/assets/9957942/c05e82a7-4040-4463-be21-2b81bba2c890)

![image](https://github.com/browningluke/terraform-provider-opnsense/assets/9957942/d850b8b4-f107-4f68-9d4b-d56cb36d2f9d)

![image](https://github.com/browningluke/terraform-provider-opnsense/assets/9957942/2552e6da-16db-4554-b95a-3f1d83bf1cfb)

**Comment by browningluke** [comment]
Hey @chrisreeves-, that error actually looks like it's from a quirk of how the os-firewall plugin works. It considers the protocol attribute case sensitive.

In that code example you showed, try set `protocol = "TCP"`.

**Comment by chrisreeves-** [comment]
Beautiful, that fixed it!

Thanks again :) :)
