### ISSUE TITLE
Support for configuring provider via environment variables

### ISSUE THREAD

**Issue by ikaruswill** [browningluke/terraform-provider-opnsense#39]
Hi there, first of all, I'd like to say, this is really cool stuff. I have always been looking forward to define my home infrastructure declaratively. Since I'm used to the world of GitOps and IaC, the mutable state of OPNsense really keeps me up at night at times. With this provider, I may finally sleep peacefully without fear of waking up to an SSD failure on my firewall and no way to understand the context of certain configurations made, a million changes later.

I was just starting to use this provider in my CI pipeline which performs the terraform actions, and I was looking to provide credentials via environment variables.

I saw that it was documented that the env vars can be used:
- [api_key](https://registry.terraform.io/providers/browningluke/opnsense/latest/docs#api_key) (String) The API key for a user. Alternatively, can be configured using the `OPNSENSE_API_KEY` environment variable.
- [api_secret](https://registry.terraform.io/providers/browningluke/opnsense/latest/docs#api_secret) (String) The API secret for a user. Alternatively, can be configured using the `OPNSENSE_API_SECRET` environment variable.
- [uri](https://registry.terraform.io/providers/browningluke/opnsense/latest/docs#uri) (String) The URI to an OPNsense host. Alternatively, can be configured using the `OPNSENSE_URI` environment variable.

However:
1. The provider running in the CI container was not able to detect the environment variables even though they were confirmed to be present.
2. I tested on local with the environment variables set and the provider did not pick them up.
3. I checked the code and found no mentions of logic reading the respective environment variables.

Questions:
1. Is configuring the provider via environment variables truly supported as documented? Did I miss that somewhere?
2. If it isn't, can I request for the support to be implemented?

**Comment by browningluke** [comment]
Hey there @ikaruswill, thanks for opening this issue!

You are totally right, it doesn't appear to be implemented. I believe I wrote the docstring intending to add the functionality later, but then I failed to make note of it and it slipped by.

I'll get this implemented right away.

**Comment by browningluke** [comment]
Auto-closed by merging #41. Will be out in the next release. Let me know if you run into any more issues and I'll re-open this issue!

**Comment by ikaruswill** [comment]
Thanks for your work on this!
