### ISSUE TITLE
Resource creation error with OPNsense 24.7.x

### ISSUE THREAD

**Issue by aglasson** [browningluke/terraform-provider-opnsense#50]
I've basically tried to create every type of resource in OPNsense with Terraform and I keep getting the same error. I can read data from existing configuration in OPNsense and outputting it in Terraform no problem at all. Its basically like the API keys are read only. I've created a key on root and also created a new user, granted all access and created a key on that user to no avail.
Has something perhaps changed in the OPNSense or Terraform latest version and stopping this provider from working perhaps?

This is my first time using OPNSense and this Terraform provider. I have years of experience with PFSense, I'm trying to move to OPNSense purely for the benefit of configuring my router with desired state IaC.

> Unable to create vlan, got error: resource not changed. result: failed. errors: map[]

I've looked at the terraform debug logs and I seem to get no more helpful information than that. If I remove any `resource` elements from my .tf file and only have `data` and `output` elements, terraform outputs the data to console perfectly with no errors.

Version info:
OPNsense: 24.7
Terraform: 1.9.5
Provider: 0.10.1

For example I get this error with the most basic of resource config, nothing else in my main.tf, terraform.tf has just my provider config:
```
resource "opnsense_route" "one_route" {
  description = "test route"
  gateway = "WAN_GW"
  network = "192.168.31.0/24"
}

**Comment by browningluke** [comment]
Hey there @aglasson 

Sorry it's not working for you, thanks for flagging this. It sounds like it might be an OPNsense 24.7 issue.

I can confirm everything works for me on:
OPNsense: 24.1
Terraform: 1.9.5
Provider: 0.10.1

I'm installing OPNsense 24.7 on a test VM now to try and troubleshoot this. I'll get back to you.

Just checking, you created API keys like this (v) here? (under System > Access > Users)
<img width="1069" alt="image" src="https://github.com/user-attachments/assets/7d19db2d-a1af-4065-bde8-af3ce9fa6cf4">

I haven't played around too much with the OPNsense RBAC, but for my setup the provider works with API keys created under the default `root` user in the `admins` group, although you said you tested this.

**Comment by browningluke** [comment]
Just got OPNsense 24.7 installed and it seems to work correctly for me.

Here is my setup verbatim:

<details><summary>TF CODE</summary>
<p>

```tf
# versions.tf

terraform {
  required_version = "~> 1.9.5"

  required_providers {
    opnsense = {
      source  = "browningluke/opnsense"
      version = "~> 0.10.0"
    }
  }
}
```

```tf
# main.tf
provider "opnsense" {
  uri        = "https://<url of opnsense>"
  api_key    = "<api key from opnsense root user>"
  api_secret = "<api secret from opnsense root user>"
}

resource "opnsense_route" "one_route" {
  description = "test route"
  gateway = "WAN-STATIC"
  network = "192.168.31.0/24"
}

```
</p>
</details> 

With this code I get the expected: `Apply complete! Resources: 1 added, 0 changed, 0 destroyed.`

This provider actually echos the requests it makes to/from OPNsense in the TF debug log. Try run: 
```
TF_LOG=DEBUG terraform apply
``` 

If you spot the bug, great! If not, redact out your private values (URL / Auth Header) and post the output here and I'll take a look.

**Comment by cjlucas** [comment]
Just for added info: I was able to reproduce this with a fresh install using the OPNsense 24.7 installer (which is a few minor versions behind.) After upgrading to the latest stable (24.7.5_3) the issue resolved itself.

**Comment by browningluke** [comment]
Thanks @cjlucas ! I'll have to take a look into which minor version the OPNsense 24.7 installer is installing.

For what it's worth, all my previous comments (where it was working) were made using `OPNsense 24.7.1-amd64`.

**Comment by cjlucas** [comment]
Oh and to clarify, this is an upstream issue. The `ansibleguy.opnsense` ansible module also showed the same issue I was able to reproduce the `{"result": "failed"}` response directly with curl.

**Comment by aglasson** [comment]
Legends! I can confirm its working fine for me after updating.
You can all blame me and my bad luck for causing this bug, I attempted to use it for the first time so some disaster was guaranteed. Just like when I buy shares... The sharemarket crashes. When I sell shares, sharemarket goes bull.

I'm super glad to see I'm not going insane... This bug had me seriously questioning my competency as an IT engineer "How can I not even get one simple test example of this tool to work.".
I also learned that the opnsense ISO installer is not remotely up to date with the latest version and after install an update is absolutely required. I was initially running Opnsense without internet access after installing it just to test it and this IAC functionality.

**Comment by aglasson** [comment]
Marking this one done. Thanks!
